// Shortener - service for short URL generation.
package main

import (
	"database/sql"
	_ "net/http/pprof"

	_ "github.com/shulganew/shear.git/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/shulganew/shear.git/internal/app"
	"github.com/shulganew/shear.git/internal/config"
	"github.com/shulganew/shear.git/internal/service"
	"github.com/shulganew/shear.git/internal/web/router"
	"github.com/shulganew/shear.git/internal/web/server"
	"github.com/shulganew/shear.git/pkg/shutdown"
	"go.uber.org/zap"
)

var (
	buildVersion string = "N/A"
	buildDate    string = "N/A"
	buildCommit  string = "N/A"
)

// @Title Shortener API
// @Description Shortener service.
// @Version 1.1

// @Contact.email shulganew@gmail.com

// @BasePath /
// @Host localhost:8080
func main() {
	app.Intro(buildVersion, buildDate, buildCommit)
	app.InitLog()

	// Root app context.
	ctx, cancel := app.InitContext()

	conf := config.NewConfig()

	var db *sql.DB
	var err error
	// If use persistent sorage - init it.
	if conf.IsDB() {
		db, err = app.InitDB(ctx, conf.GetDSN())
		if err != nil {
			db = nil
			conf.SetIsDB(false)
			zap.S().Errorln("Can't connect to Database!", err)
		}
		// Exit after all components will be done. Database should be closed after all components complited.
		defer func() {
			err := db.Close()
			if err != nil {
				zap.S().Errorln("Error closing DB: ", err)
			} else {
				zap.S().Infoln("DB closed.")
			}
		}()
	}

	// Use fan-In pattern for storing data from delete requests.
	delCh := make(chan service.DelBatch, 100)
	defer close(delCh)

	// Init application.
	short, backup, del := app.InitApp(ctx, *conf, db, delCh)

	// Create router.
	rt := router.RouteShear(conf, short, db, del)

	// Error channel.
	componentsErrs := make(chan error, 1)

	// Start web server.
	webDone := server.ShortenerServer(ctx, conf, componentsErrs, rt)

	// Update deleted shorts from common fan-In channel.
	delDone := app.DeleteShort(ctx, short, delCh)

	//Graceful shutdown.
	shutdown.Graceful(ctx, cancel, componentsErrs)

	// Waiting http server shuting down.
	<-webDone

	// Waiting delete service.
	<-del.Stop()

	// Wating async writing deleded shorts to DB.
	<-delDone
	zap.S().Infoln("All shorts from del servise are deleted.")

	// Backup all shorts.
	if conf.IsBackup() {
		service.BackupShorts(short, *backup)
	}

	zap.S().Infoln("App done.")
}
