// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.12.4
// source: internal/grpcs/proto/short.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetURLRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Brief string `protobuf:"bytes,1,opt,name=brief,proto3" json:"brief,omitempty"`
}

func (x *GetURLRequest) Reset() {
	*x = GetURLRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpcs_proto_short_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLRequest) ProtoMessage() {}

func (x *GetURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpcs_proto_short_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLRequest.ProtoReflect.Descriptor instead.
func (*GetURLRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpcs_proto_short_proto_rawDescGZIP(), []int{0}
}

func (x *GetURLRequest) GetBrief() string {
	if x != nil {
		return x.Brief
	}
	return ""
}

type GetURLResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Origin string `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
}

func (x *GetURLResponse) Reset() {
	*x = GetURLResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpcs_proto_short_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLResponse) ProtoMessage() {}

func (x *GetURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpcs_proto_short_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLResponse.ProtoReflect.Descriptor instead.
func (*GetURLResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpcs_proto_short_proto_rawDescGZIP(), []int{1}
}

func (x *GetURLResponse) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

type SetURLRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Brief string `protobuf:"bytes,1,opt,name=brief,proto3" json:"brief,omitempty"`
}

func (x *SetURLRequest) Reset() {
	*x = SetURLRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpcs_proto_short_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetURLRequest) ProtoMessage() {}

func (x *SetURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpcs_proto_short_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetURLRequest.ProtoReflect.Descriptor instead.
func (*SetURLRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpcs_proto_short_proto_rawDescGZIP(), []int{2}
}

func (x *SetURLRequest) GetBrief() string {
	if x != nil {
		return x.Brief
	}
	return ""
}

type SetURLResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Origin string `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
}

func (x *SetURLResponse) Reset() {
	*x = SetURLResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpcs_proto_short_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetURLResponse) ProtoMessage() {}

func (x *SetURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpcs_proto_short_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetURLResponse.ProtoReflect.Descriptor instead.
func (*SetURLResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpcs_proto_short_proto_rawDescGZIP(), []int{3}
}

func (x *SetURLResponse) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

var File_internal_grpcs_proto_short_proto protoreflect.FileDescriptor

var file_internal_grpcs_proto_short_proto_rawDesc = []byte{
	0x0a, 0x20, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x73,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x67, 0x72, 0x70, 0x63, 0x22, 0x25, 0x0a,
	0x0d, 0x47, 0x65, 0x74, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x62, 0x72, 0x69, 0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62,
	0x72, 0x69, 0x65, 0x66, 0x22, 0x28, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x55, 0x52, 0x4c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x22, 0x25,
	0x0a, 0x0d, 0x53, 0x65, 0x74, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x62, 0x72, 0x69, 0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x62, 0x72, 0x69, 0x65, 0x66, 0x22, 0x28, 0x0a, 0x0e, 0x53, 0x65, 0x74, 0x55, 0x52, 0x4c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x32,
	0x85, 0x01, 0x0a, 0x05, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x3d, 0x0a, 0x06, 0x47, 0x65, 0x74,
	0x55, 0x52, 0x4c, 0x12, 0x18, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x47, 0x65, 0x74, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e,
	0x73, 0x68, 0x6f, 0x72, 0x74, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x52, 0x4c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x06, 0x53, 0x65, 0x74, 0x55,
	0x52, 0x4c, 0x12, 0x18, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53,
	0x65, 0x74, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x65, 0x74, 0x55, 0x52, 0x4c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x11, 0x5a, 0x0f, 0x73, 0x68, 0x6f, 0x72, 0x74,
	0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_internal_grpcs_proto_short_proto_rawDescOnce sync.Once
	file_internal_grpcs_proto_short_proto_rawDescData = file_internal_grpcs_proto_short_proto_rawDesc
)

func file_internal_grpcs_proto_short_proto_rawDescGZIP() []byte {
	file_internal_grpcs_proto_short_proto_rawDescOnce.Do(func() {
		file_internal_grpcs_proto_short_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_grpcs_proto_short_proto_rawDescData)
	})
	return file_internal_grpcs_proto_short_proto_rawDescData
}

var file_internal_grpcs_proto_short_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_grpcs_proto_short_proto_goTypes = []interface{}{
	(*GetURLRequest)(nil),  // 0: shortgrpc.GetURLRequest
	(*GetURLResponse)(nil), // 1: shortgrpc.GetURLResponse
	(*SetURLRequest)(nil),  // 2: shortgrpc.SetURLRequest
	(*SetURLResponse)(nil), // 3: shortgrpc.SetURLResponse
}
var file_internal_grpcs_proto_short_proto_depIdxs = []int32{
	0, // 0: shortgrpc.Users.GetURL:input_type -> shortgrpc.GetURLRequest
	2, // 1: shortgrpc.Users.SetURL:input_type -> shortgrpc.SetURLRequest
	1, // 2: shortgrpc.Users.GetURL:output_type -> shortgrpc.GetURLResponse
	3, // 3: shortgrpc.Users.SetURL:output_type -> shortgrpc.SetURLResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_grpcs_proto_short_proto_init() }
func file_internal_grpcs_proto_short_proto_init() {
	if File_internal_grpcs_proto_short_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_grpcs_proto_short_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetURLRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_grpcs_proto_short_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetURLResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_grpcs_proto_short_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetURLRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_grpcs_proto_short_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetURLResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_grpcs_proto_short_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpcs_proto_short_proto_goTypes,
		DependencyIndexes: file_internal_grpcs_proto_short_proto_depIdxs,
		MessageInfos:      file_internal_grpcs_proto_short_proto_msgTypes,
	}.Build()
	File_internal_grpcs_proto_short_proto = out.File
	file_internal_grpcs_proto_short_proto_rawDesc = nil
	file_internal_grpcs_proto_short_proto_goTypes = nil
	file_internal_grpcs_proto_short_proto_depIdxs = nil
}
